apiVersion: v1
kind: ConfigMap
metadata:
  name: modular-platform-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"

  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Username: "guest"

  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_SERVICE_NAME: "modular-platform-api"