apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: modular-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.modular-platform.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: modular-platform
                port:
                  number: 80